# SQLite version 3.x
#   gem 'activerecord-jdbcsqlite3-adapter'
#
# Configure Using Gemfile
# gem 'activerecord-jdbcsqlite3-adapter'
#
default: &default
  adapter: sqlite3

development:
  <<: *default
  database: /etc/toy/db/development.sqlite3

production:
  <<: *default
  database: /etc/toy/db/production.sqlite3
