#! /bin/sh
### BEGIN INIT INFO
# Provides: toy
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Toy App
# Description: This file starts and stops Toy app
#
### END INIT INFO

export $TOY_APP_HOME=

case "$1" in
 start)
   su root -c $TOY_APP_HOME/bin/startup.sh
   ;;
 stop)
   su root -c $TOY_APP_HOME/bin/shutdown.sh
   sleep 10
   ;;
 restart)
   su root -c $TOY_APP_HOME/bin/shutdown.sh
   sleep 20
   su root -c $TOY_APP_HOME/bin/startup.sh
   ;;
 *)
   echo "Usage: toy {start|stop|restart}" >&2
   exit 3
   ;;
esac