default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: /etc/simple/db/development.sqlite3

production:
  <<: *default
  database: /etc/simple/db/development.sqlite3